Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,8 +33,8 @@ jobs:
             exit 1
           fi
           
-          gzip -d wasm1/exportgodotlab.wasm.gz || { echo "Decompression failed ❌"; exit 1; }
-          if [ -f wasm1/exportgodotlab.wasm ]; then
+          gzip -d exportgodotlab.wasm.gz || { echo "Decompression failed ❌"; exit 1; }
+          if [ -f exportgodotlab.wasm ]; then
             echo "WASM file decompressed ✅"
           else
             echo "WASM file NOT decompressed ❌"
