Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,16 +23,17 @@ jobs:
      # ✅ Check if WASM file exists and decompress it
       - name: Decompress .wasm file
         run: |
-          curl -L https://raw.githubusercontent.com/minec-c/satnotcanvasxz/wasm1/exportgodotlab.wasm.gz -o exportgodotlab.wasm.gz
+          curl -L https://raw.githubusercontent.com/minec-c/satnotcanvasxz/main/wasm1/exportgodotlab.wasm.gz -o exportgodotlab.wasm.gz
           
           if [ -f exportgodotlab.wasm.gz ]; then
             echo "WASM file found ✅"
-            gzip -d wasm1/exportgodotlab.wasm.gz || { echo "Decompression failed ❌"; exit 1; }
+            
           else
             echo "WASM file NOT found ❌"
             exit 1
           fi
-
+          
+          gzip -d wasm1/exportgodotlab.wasm.gz || { echo "Decompression failed ❌"; exit 1; }
           if [ -f wasm1/exportgodotlab.wasm ]; then
             echo "WASM file decompressed ✅"
           else
@@ -40,7 +41,9 @@ jobs:
             exit 1
           fi
 
-
+          mkdir -p wasm1
+          mv exportgodotlab.wasm wasm1/exportgodotlab.wasm
+          
       - name: Download and decompress .pck file directly
         run: |
           curl -L https://raw.githubusercontent.com/minec-c/satnotcanvas/satnotcanvas2/godotapk/exportgodotlab.pck.gz -o exportgodotlab.pck.gz
