Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,17 +19,27 @@ jobs:
           ref: main
 
 
-
-      - name: Download and decompress .pck file directly
+     # ✅ Check if WASM file exists and decompress it
+      - name: Decompress .wasm file
         run: |
-          gzip -d wasm1/exportgodotlab.wasm.gz || { echo "Decompression failed ❌"; exit 1; }
-          if [ -f exportgodotlab.wasm ]; then
+          if [ -f wasm1/exportgodotlab.wasm.gz ]; then
+            echo "WASM file found ✅"
+            gzip -d wasm1/exportgodotlab.wasm.gz || { echo "Decompression failed ❌"; exit 1; }
+          else
+            echo "WASM file NOT found ❌"
+            exit 1
+          fi
+
+          if [ -f wasm1/exportgodotlab.wasm ]; then
             echo "WASM file decompressed ✅"
           else
             echo "WASM file NOT decompressed ❌"
             exit 1
           fi
-          
+
+
+      - name: Download and decompress .pck file directly
+        run: |
           curl -L https://raw.githubusercontent.com/minec-c/satnotcanvas/satnotcanvas2/godotapk/exportgodotlab.pck.gz -o exportgodotlab.pck.gz
 
           if [ -f exportgodotlab.pck.gz ]; then
