Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,16 +18,19 @@ jobs:
         with:
           ref: main
 
-      - name: Download and decompress .pck file directly
+      - name: Decompress .wasm file
         run: |
-          gzip -d exportgodotlab.wasm.gz || { echo "Decompression failed ❌"; exit 1; }
+          gzip -d wasm1/exportgodotlab.wasm.gz || { echo "Decompression failed ❌"; exit 1; }
           if [ -f exportgodotlab.wasm ]; then
             echo "WASM file decompressed ✅"
           else
             echo "WASM file NOT decompressed ❌"
             exit 1
           fi
-          
+        # gzip -d wasm1/exportgodotlab.wasm.gz
+
+      - name: Download and decompress .pck file directly
+        run: |
           curl -L https://raw.githubusercontent.com/minec-c/satnotcanvas/satnotcanvas2/godotapk/exportgodotlab.pck.gz -o exportgodotlab.pck.gz
 
           if [ -f exportgodotlab.pck.gz ]; then
